name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Follow the syntax"
        default: v1.1
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        dbpassword: ${{ secrets.dbpassword }}
      run: | 
        docker build . --file Dockerfile -t mysql:${{ inputs.tag }}
        docker run --name mysql -e MYSQL_ROOT_PASSWORD=$dbpassword -d mysql:${{ inputs.tag }}
        docker exec -i mysql sh -c 'exec mysql -u root -$dbpassword' < script.sql