name: "Docker and MySql DB"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Follow the syntax"
        default: v1.1
        required: true

jobs:
  build-mysql:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      env:
        dbpassword: ${{ secrets.dbpassword }}
        token: ${{ secrets.jfrogtoken }}
      run: |
        docker build . --file Dockerfile -t mysql:${{ inputs.tag }}
        docker run --name mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.dbpassword }} -d mysql:${{ inputs.tag }}
        dbhost=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql)
        sleep 15
        echo $dbhost
        docker exec -i mysql sh -c "exec mysql -u root -p${{ secrets.dbpassword }}" < script.sql
        docker exec -i mysql sh -c "exec mysql -u root -p${{ secrets.dbpassword }}" < test.sql
        echo $TOKEN |docker login -usimone84.an@gmail.com simone84.jfrog.io --password-stdin
        docker tag mysql:${{ inputs.tag }} simone84.jfrog.io/img/mysql:${{ inputs.tag }}
        docker push simone84.jfrog.io/img/mysql:${{ inputs.tag }}